---
- hosts: ocp
  tasks:
  - name: Unarchive a file that needs to be downloaded
    unarchive:
      src: http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz
      dest: /opt
      remote_src: yes
